### ISSUE TITLE
Katex degree sign

### ISSUE THREAD

**Issue by vascoV** [lingarajsankaravelu/Katex#12]
Hello, At first nice work!

I am using Katex MathView in my andorid application and have some issues with despaying the degree sign, however all the other stuff and sumbold are incredibly working!

I have a function which takes as input the actual math foprmula as a string and surround it with '$$' so I don't have to do it for each formula superately. However, when it come to degree is not working for some reason, but on the katex editor works fine (https://khan.github.io/KaTeX/)

The syntax that I am using is the following: 
```
String formula;
private String addSign(String formula) {
        String prefixSuffix = "$$";
        return prefixSuffix + option + prefixSuffix;
    }
formula = addSign("50\degree");
```

The output is -> $$50\degree$$ instead of 50°

**Comment by Aiosa** [comment]
Hi there, really hard to say where the problem lies, in my app degree works just fine. Just display this formula inside MathView - it should work.
Either declare it progmatically:
```
MathView mt = new MathView(this);
mt.setDisplayText(formula);
someLayout.addView(mt);
```
Or find it by id and set this formula to it.

Also, you can use just "°" sign, which is on a PC keyboard as well. If you want to display it with 'math font', just add '$$' -> $$50°$$ For me this solution seems to be even better, you don't have to write the whole \degree thing, yet it works without $$ as well.

**Comment by vascoV** [comment]
Yeah that's a point but I am using various formulas, not all of them are using the degree symbol some are using another syntax etc, so adding the  "°" will not work for me!
However, I found a solution instead using the **$$\degree$$** I am using this -> **$$50^\circ$$**,
which actually is doing the same thing a simple circle jus added as the power of the number.

**Comment by moliata** [comment]
Hello, just use `50^{\circ}`, best regards.

**Comment by vascoV** [comment]
closing this issue
