### ISSUE TITLE
Loading latex equations

### ISSUE THREAD

**Issue by Shatrujeet** [lingarajsankaravelu/Katex#14]
Is there a way to make the view render latex equations faster when loading content from a local database?Also any way to get the height of the loaded content,OnPagefinished() does not work with the view?

**Comment by Aiosa** [comment]
I don't think there's way to get the mathView height since it depends on "dynamic/static webpage" and the content is being loaded even after onPagefinished event.

 It's possible though to set it to certain size and allow the content to scroll.

Idk about speed but I think they would speed it up if it was possible. If you need to speed up loading from database, I suggest to get the data from asynctask before you need the data, eg. try to get the data behind scenes for the user while another activity is running (if it's possible) - for example generating random questions for some sort of practice app - just get the data for next question while user answers the previous and then all your phone needs to do is fed this data to mathview in the next activity)

But as I mentioned, mathView is kind of webView which is meant to load its content even AFTER the activity starts (some webpages may be huge, it needs to wait for server response etc...)

Obviously there is a way to solve this, but I expect it to be too complex to be worth trying (because if it hadn't somebody would have already done it). You need to modify webView so the activity will wait for webView content to be loaded. Then, you need to modify mathView to extend your modified webView. Then, your activity will wait for formulas to be loaded. 
`public class myMathView extends myWebView`
just copypaste the source code, but idk how to set up webView to let the activity know to wait...

**Comment by Aiosa** [comment]
Also, the following usage seems to be much more effective:

instead of layout like this:
TEXTVIEW
MATHVIEW
TEXTVIEW
MATHVIEW
TEXTVIEW

do this:
MATHVIEW (covering the whole screen)

with content:
some text $$ first formula $$ other text $$ second formula $$ another text $$ next formula $$ etc

it seems to be a bit faster and it allows you to use html formatting for your text as well..

**Comment by Shatrujeet** [comment]
Right,Thank you very much,I really appreciate your help in this matter!!
