### ISSUE TITLE
How can I not change lines?

### ISSUE THREAD

**Issue by zhaolf888** [lingarajsankaravelu/Katex#15]
How can I not change lines? I want the formula and other text to appear in a row。

**Comment by Aiosa** [comment]
I think it is possible only with modifying the CSS style sheets, since pure Katex supports inline formulas, whereas lingarajsankaravelu breaks line every time regardless the number of "$". You will need to look deeper into source code and find the solution for this because:

1) The project owner doesn't have time to maintain this project
1) Nobody else really knows where it should be modified

Try to look into MathView.java source code, there are (in-code) all the resources used - CSS sheets, katex engine etc. so you can look into it and possibly find the solution. Or, give up :)

**Comment by zlfaiyh** [comment]
Thank you for your answer！

**Comment by zhaolf888** [comment]
Thank you for your answer！

**Comment by Aiosa** [comment]
I would look into one of those files:
file:///android_asset/katex/katex.min.css"
file:///android_asset/katex/katex.min.js"
file:///android_asset/katex/contrib/auto-render.min.js

**Comment by lingarajsankaravelu** [comment]
@zlfaiyh the code in the modification branch supports multiline.  I will be releasing as an update to bintray sooner or later.
