### ISSUE TITLE
its not issue but i want to know about these two thinks

### ISSUE THREAD

**Issue by eranilsharma** [lingarajsankaravelu/Katex#24]
how I hide scrollbar indicator and
It reloads again and again on Recyclerview notifyDataSetChanged 

thanks

**Comment by lingarajsankaravelu** [comment]
1. Currently hiding scrollbar don't have a seperate attribute. so if you set the app:setClickable="true", the scrollbars will be disabled.
2. [To make recyclerview aware of loaded data refer this](https://medium.com/@hanru.yeh/recyclerviews-views-are-blinking-when-notifydatasetchanged-c7b76d5149a2)

**Comment by eranilsharma** [comment]
thanks, bro u help me lot

**Comment by eranilsharma** [comment]
Is I set a single line and multiline my webview on the click on it?

**Comment by lingarajsankaravelu** [comment]
@eranilsharma its a click listener, doesn't matter whether yours is a single or multiline. There is  proper  sample code in this repo itself , which contain different data formats, you can play with and figure out how it works for the application that you  design  or develop.

I removed your comment from the issue 6   because of the following reason. What you are trying to get clarification on and the place where you posted your comment on  were two different things,  doesn't have any relation or whatsoever. I guess you are new to the world of programming, if so please go through this.
[how to ask a question etiquette](https://stackoverflow.com/help/how-to-ask).

###Please Read the documentation from readMe and play with the sample code.

**Comment by eranilsharma** [comment]
thanks bro


*Android Developer <https://www.linkedin.com/in/eranilsharma/>*
